name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Enable fs-verity on /
      run: sudo tune2fs -O verity $(findmnt -vno SOURCE /)
    - uses: actions/checkout@v4
    - run: cargo build --verbose
    - run: cargo fmt --check
    - run: cargo clippy -- -Dwarnings
    - run: cargo test --verbose
